Documentation improvements
hpcflow/hpcflow-new pull request #699
Opened 2024-07-23 11:06 UTC by dkfellows

Working on improving documentation.

- [ ] CI building of docs (or at least the Sphinx part)
- [ ] Fix errors in doc build
- [ ] Add missing method docs

2024-08-13 15:11 UTC, dkfellows commented
That's all the remaining faults that I can fix. The ones that are left (all warnings) are due to the combination of importing the `cli` stuff from `hpcflow.sdk` into `hpcflow.app` and the CLI documentation being generated by click; the place where it's going wrong is just too deep within the nest of generated stuff.

2024-09-23 15:08 UTC, aplowman requested changes
Excellent, thanks!

2024-09-23 15:08 UTC, aplowman commented on hpcflow/sdk/core/loop.py
> +    ::py:class:`~hpcflow.app.Workflow`.
There is an extra colon here I think.

2024-09-24 12:44 UTC, dkfellows commented on hpcflow/sdk/core/loop.py
> +    ::py:class:`~hpcflow.app.Workflow`.
Oops

2024-09-24 13:15 UTC, aplowman approved these changes

2024-09-24 13:25 UTC, merged